global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: ingestion-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ingestion-service:8095']

  - job_name: analytics-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['analytics-service:8085']

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8082']
