spring.application.name=ingestion-service
server.port=8095
spring.kafka.bootstrap-servers=broker:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Logging
logging.level.root=INFO
logging.level.com.coinstream=DEBUG
