spring.application.name=ingestion-service
server.port=8095
spring.kafka.bootstrap-servers=broker:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Logging
logging.level.root=INFO
logging.level.com.coinstream=DEBUG

# Custom Configuration
kafka.topic.prices=market.prices
binance.ws.url=wss://stream.binance.com:9443/stream?streams=btcusdt@trade/ethusdt@trade/solusdt@trade
binance.ws.reconnect.delay.seconds=5

# Modernization Features
spring.threads.virtual.enabled=true
logging.structured.format.console=logstash
management.tracing.sampling.probability=1.0
